var videoTitle=document.title || 'video';
		videoTitle=videoTitle.replace(/\s*\-\s*YouTube$/i, '').replace(/'/g, '\'').replace(/^\s+|\s+$/g, '').replace(/\.+$/g, '');
		videoTitle=videoTitle.replace(/[:"\?\*]/g, '').replace(/[\|\\\/]/g, '_');  
		if (((window.navigator.userAgent || '').toLowerCase()).indexOf('windows') >= 0) {
		videoTitle=videoTitle.replace(/#/g, '').replace(/&/g, '_');  
		} else {
		videoTitle=videoTitle.replace(/#/g, '%23').replace(/&/g, '%26');  
		}
		var capurl = document.getElementById("listazeta");
		var urlvideo = capurl.getElementsByTagName("a")[0].href;
		var forma = document.createElement("form");
		forma.action = "https://api.cloudconvert.com/convert";
		forma.method = "POST";
		forma.enctype = "multipart/form-data";
		forma.id = "zetaforma";
		var apikey = document.createElement("input");
		apikey.type = "hidden";
		apikey.name = "apikey";
		apikey.value = "p7Ekr9t1mJaCvHp9X9V29YwtFrg_dj41NOxaErj-qvdUFf-S_We5vO7xsmv901KMG1jvLAqvHhXxRUn8nhuqjA";
		forma.appendChild(apikey);
		var formatoin = document.createElement("input");
		formatoin.type = "hidden";
		formatoin.name = "inputformat";
		formatoin.value = "mp4";
		forma.appendChild(formatoin);
		var formatoout = document.createElement("input");
		formatoout.type = "hidden";
		formatoout.name = "outputformat";
		formatoout.value = "mp3";
		forma.appendChild(formatoout);
		var downlo = document.createElement("input");
		downlo.type = "hidden";
		downlo.name = "input";
		downlo.value = "download";
		forma.appendChild(downlo);
		var urlarq = document.createElement("input");
		urlarq.type = "hidden";
		urlarq.name = "file";
		urlarq.value = urlvideo;
		forma.appendChild(urlarq);
		var nomefim = document.createElement("input");
		nomefim.type = "hidden";
		nomefim.name = "filename";
		nomefim.value = videoTitle + ".mp4";
		forma.appendChild(nomefim);
		var espera = document.createElement("input");
		espera.type = "hidden";
		espera.name = "wait";
		espera.value= "true";
		forma.appendChild(espera);
		var download = document.createElement("input");
		download.type = "hidden";
		download.name = "download";
		download.value = "true";
		forma.appendChild(download);
		var enviar = document.createElement("input");
		enviar.type = "submit";
		enviar.value = "Converter para MP3";
		var forma = document.getElementById("zetaforma");
		forma.appendChild(enviar);
		document.body.appendChild(forma);
